name: "Playwright Remocon"
slug: "playwright_remocon"
version: "1.0.2"
description: "Scarica automaticamente il file Excel da Remocon usando Playwright"

arch:
  - aarch64

startup: services
boot: auto
host_network: true

options: {}
schema: {}
